### ISSUE TITLE
部署有问题

### ISSUE THREAD

**Issue by pifuant** [horan-geeker/fabric-on-k8s#2]
你好

>       hostPath:
>             # change this to current dir path
>             path: /Users/hejunwei/k8s/fabric-on-k8s/

把 path改为 path: MYPATH

其他需要改什么？

**Comment by junwei000** [comment]
这个是在本地部署测试是 ok 的，线上要用 NFS 部署，你部署遇到什么问题，报错吗？

**Comment by pifuant** [comment]
order， peer config error

可以留给微信吗， 好请教你， 哈哈

**Comment by junwei000** [comment]
he_jun_wei

**Comment by pifuant** [comment]
thanks
